[tool.poetry]
name = "homeassistant-greenchoice"
version = "1.2.5"
description = ""
authors = ["Baris Demirdelen <barisdemirdelen@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
homeassistant = "^2022.5.2"
requests = "^2.27.1"
beautifulsoup4 = "^4.11.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
